### ISSUE TITLE
Add CAA reproduction to this repository

### ISSUE THREAD

**Issue by dtch1997** [steering-vectors/steering-vectors#12]
Under `contrib` or `experiments` subfolder? 

The goal is to demonstrate that it's easy to reproduce a CAA-style approach here

**Comment by dtch1997** [comment]
@chanind curious about your thoughts

**Comment by chanind** [comment]
I'm personally not a fan of adding experiments to this repo, as I view this as more of a tool for doing research rather than research itself. We have a test case which asserts that this library gives identical results to CAA in steering [test_steering_vector.py#L60-L83](https://github.com/steering-vectors/steering-vectors/blob/main/tests/test_steering_vector.py#L60-L83), and that it gives identical results to CAA in training [test_train_steering_vector.py#L60-L120](https://github.com/steering-vectors/steering-vectors/blob/main/tests/test_train_steering_vector.py#L60-L120), which should give confidence that this library is capable of reproducing CAA results given the same inputs.

I feel like adding an `experiments` dir would be like adding an `experiments` dir to PyTorch, which feels strange since PyTorch is a library not a research paper. We could add `examples` with some jupyter notebooks showing how to use the library to reproduce CAA results though, for example.

**Comment by dtch1997** [comment]
Subsumed by #13
