### ISSUE TITLE
`train_steering_vector` can't accept data of type `SteeringVectorTrainingSample` 

### ISSUE THREAD

**Issue by dtch1997** [steering-vectors/steering-vectors#17]
Currently the type annotation is like this: 

```python
@torch.no_grad()
def train_steering_vector(
    model: nn.Module,
    tokenizer: PreTrainedTokenizerBase,
    training_samples: list[SteeringVectorTrainingSample] | list[tuple[str, str]],
    layers: Optional[list[int]] = None,
    layer_type: LayerType = "decoder_block",
    layer_config: Optional[ModelLayerConfig] = None,
    move_to_cpu: bool = False,
    read_token_index: int = -1,
    show_progress: bool = False,
    aggregator: Aggregator = mean_aggregator,
    # TODO: add more options to control training
) -> SteeringVector:
```

However, the function assumes that `training_samples` is a `list[tuple[str, str]]`, as seen by the following code snippet: 
```python
    for pos_prompt, neg_prompt in tqdm(
        training_samples, disable=not show_progress, desc="Training steering vector"
    ):
```

**Comment by chanind** [comment]
`SteeringVectorTrainingSample` is also a tuple (it extends `NamedTuple`), so it should be fine to use it as a tuple as well. This is why MyPy is fine with the typings as stated. I mainly added that typing in case we wanted to add some extra options in the future beyond what's possible in the standard `tuple[str, str]`, or for power users who really want some more explicit typings for use in a dataloader or something.

I figured it's good to support the simple `tuple[str, str]` version since most researchers don't understand type hints and get confused by dataclasses, so would understand the `tuple[str, str]` more intuitively.
